<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="IntegrationDays.SignalRDemo.Dashboard" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-1.0.0-rc1.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="<%= ResolveUrl("~/signalr/hubs") %>"></script>
    <!--Add script to update the page--> 
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub. 
            var notify = $.connection.notifyHub;
            // Create a function that the hub can call to broadcast messages.
            notify.client.addAccident = function (message) {
                $('#accidentcount').html(parseInt($('#accidentcount').html(), 10) + 1);
                $('#accidentlist').append('<div>Message is ' + message + '</div>');
            };
            
            // Start the connection.
            $.connection.hub.start();
        });
    </script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        Safety First!<br />
        <asp:Label ID="accidentcount" runat="server" Text="0"></asp:Label> accidents so far today!
      

    <div id="accidentlist" style="height:300px; width:220px; overflow-y: scroll; overflow-x: hidden; border:1px solid black; padding:0px;background-color:Silver">
    <div>Startup Message<br /></div>
    </div>


    </div>
    </form>
</body>
</html>
