<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="InventoryLookup.aspx.cs" Inherits="IntegrationDays.SignalRDemo.InventoryLookup" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Inventory Lookup</title>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-1.0.0-rc1.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="<%= ResolveUrl("~/signalr/hubs") %>"></script>
    <!--Add script to update the page--> 
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub. 
            var notify = $.connection.notifyHub;

            // Create a function that the hub can call to broadcast messages.
            notify.client.addLookupResponse = function (providerId, stockAmount) {
                $('#responselist').append('<div>Provider <b>' + providerId + '</b> has <b>' + stockAmount + '</b> units in stock.</div>');
            };

            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#dolookup').click(function () {
                    notify.server.lookupInventory($('#itemid').val());
                    $('#responselist').append('<div>Checking global inventory ...</div>');
                });
            });
        });
    </script>
</head>
<body style="background-color:black;font-family:'Segoe UI'">
    <div>
        <div style="margin-left:auto;margin-right:auto; width:500px; height:400px; background-color:white;border:4px solid #6699FF">
            <div style="width:490px; height:50px;padding-left:10px; background-color:#6699FF;color:white;font-size:x-large">Inventory Lookup</div><br />
            <div style="padding:10px"> 
               <b>Item Number:</b> <input type="text" id="itemid" />&nbsp;&nbsp;
                <input type="button" id="dolookup" value="Lookup" /><br /><br />
                <div id="responselist">
                </div>
            </div>
        </div>
    </div>
</body>
</html>
