//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationDays.SignalRDemo.LookupService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LookupService.IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInven" +
        "toryRequestPort")]
    public interface IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPort {
        
        // CODEGEN: Generating message contract since the operation LookupInventory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="LookupInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IntegrationDays.SignalRDemo.LookupService.LookupInventoryResponse LookupInventory(IntegrationDays.SignalRDemo.LookupService.LookupInventoryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IntegrationDays.SignalRDemo.BT.InventoryLookupRequest_XML")]
    public partial class InventoryLookupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIdField;
        
        private string itemIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LookupInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationDays.SignalRDemo.BT.InventoryLookupRequest_XML", Order=0)]
        public IntegrationDays.SignalRDemo.LookupService.InventoryLookupRequest InventoryLookupRequest;
        
        public LookupInventoryRequest() {
        }
        
        public LookupInventoryRequest(IntegrationDays.SignalRDemo.LookupService.InventoryLookupRequest InventoryLookupRequest) {
            this.InventoryLookupRequest = InventoryLookupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LookupInventoryResponse {
        
        public LookupInventoryResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortChannel : IntegrationDays.SignalRDemo.LookupService.IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortClient : System.ServiceModel.ClientBase<IntegrationDays.SignalRDemo.LookupService.IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPort>, IntegrationDays.SignalRDemo.LookupService.IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPort {
        
        public IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortClient() {
        }
        
        public IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationDays.SignalRDemo.LookupService.LookupInventoryResponse IntegrationDays.SignalRDemo.LookupService.IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPort.LookupInventory(IntegrationDays.SignalRDemo.LookupService.LookupInventoryRequest request) {
            return base.Channel.LookupInventory(request);
        }
        
        public void LookupInventory(IntegrationDays.SignalRDemo.LookupService.InventoryLookupRequest InventoryLookupRequest) {
            IntegrationDays.SignalRDemo.LookupService.LookupInventoryRequest inValue = new IntegrationDays.SignalRDemo.LookupService.LookupInventoryRequest();
            inValue.InventoryLookupRequest = InventoryLookupRequest;
            IntegrationDays.SignalRDemo.LookupService.LookupInventoryResponse retVal = ((IntegrationDays.SignalRDemo.LookupService.IntegrationDays_SignalRDemo_BT_ProcessInventoryRequest_ReceiveInventoryRequestPort)(this)).LookupInventory(inValue);
        }
    }
}
